/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmartHomeDSLStandaloneSetup extends SmartHomeDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new SmartHomeDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
