/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.idm.xtext.ide


/**
 * Use this class to register ide components.
 */
class SmartHomeDSLIdeModule extends AbstractSmartHomeDSLIdeModule {
}
